### PR TITLE
Move to pyproject.toml from setup.py

### PR DESCRIPTION
**Pull request by patrickboateng**
Changes have been made to move the project configuration from `setup.py` to `pyproject.toml`.

### CODE REVIEW

**Review by nyggus — APPROVED** [review]
Great, Patrick! I only changed the version to 0.2.0, as it's too big a change to call it patch. Thanks for your great work here!

**Comment by nyggus** [comment]
Patrick, please accept the review - since I was the last committer, you need to accept the MR, too.

**Review by patrickboateng — COMMENTED** [review]
All good.

**Review by patrickboateng — COMMENTED** [review]
all files reviewed.

**Comment by patrickboateng** [comment]
I have reviewed all the required files. Thanks

**Review by nyggus — APPROVED** [review]
👍

**Comment by nyggus** [comment]
> I have reviewed all the required files. Thanks

The pull request still requires your approval, as I was the last committer.

**Comment by patrickboateng** [comment]
And it is saying here that pull request author cannot approve their own pull request. I am currently confused.

**Comment by nyggus** [comment]
> And it is saying here that pull request author cannot approve their own pull request. I am currently confused.

Wow! It seems we're stuck. In that case, I will merge by bypassing branch protections. Seems like a strange scenario that GitHub should deal with somehow. Thanks!

**Comment by nyggus** [comment]
Version: 0.7.0

The `pyproject.toml` file has been added, and now:
* `makepackage` is packaged and manages its dependencies using the pyproject.toml backend, so to say
* packages created using `makepackage` are packaged and managed the same way

**Pull request merged**
